services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"


  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_beat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: celery -A app.celery_app.celery_app beat --loglevel=info

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: flower
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: celery -A app.celery_app.celery_app flower --loglevel=info
    ports:
      - "5555:5555"
    

volumes:
  postgres_data:

